### ISSUE TITLE
Refresh on connection

### ISSUE THREAD

**Issue by alex-Arc** [bitfocus/companion-module-adder-xdip#1]
Can confirm that it works on Win10

It would be very helpful if the module ran `Refresh Channel List` and `Get Connected Channel` 
when the connection is first established

**Comment by daniep01** [comment]
Hi,

Yes, it will work on Windows10.

Those commands are sent when the module is initialised, are you not seeing any data returned?

**Comment by daniep01** [comment]
Closed due to lack of information
